version: 2.1

#orbs:
#  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  # Pre Build Checks
  do_linting_and_testing_job:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: "Run Gradle Lint"
          command: ./gradlew lintDebug
      - run:
          name: "Run Gradle Test"
          command: ./gradlew test
  # Actual Building
  build_apk_job:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: "Run gradlew version"
          command: |
            ./gradlew -version
      - run:
          name: Do actual Build
          command:  ./gradlew assembleDebug

#workflows:
#  version: 2
#  test-and-build-wf:
#    jobs:
#      - do_linting_and_testing_job
#      - build_apk_job:
#          requires:
#            do_linting_and_testing_job