version: 2.1

#orbs:
#  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  # Actual Building
  build:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: "Run gradlew version"
          command: |
            ./gradlew -version
      - run:
          name: Do actual Build
          command:  ./gradlew assembleDebug
      - run: echo "The artifacts is at ./app/build/outputs/apk/debug"
      - run: ls -l ./app/build/outputs/apk/debug/
      - store_artifacts:
          path: ./app/build/outputs/apk/debug
          destination: app-debug
      - store_artifacts:
          path: ./mealdb/build/outputs/aar
  # Pre Build Checks
  test:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: "Run Spotless Check"
          command: ./gradlew spotlessCheck
      - run:
          name: "Run Detekt"
          command: ./gradlew detekt
      - run:
          name: "Run Lint"
          command: ./gradlew lintDebug
      - run:
          name: "Run Unit Test"
          command: ./gradlew test
      - run:
          name: "Run Jacoco Test Report"
          command: ./gradlew jacocoTestReportDebug
      - store_artifacts:
          path: ./mealdb/build/reports
workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
