version: 2.1

#orbs:
#  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build_apk:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: "Run gradlew version"
          command: |
            ./gradlew -version
      - run:
          name: Do actual Build
          command:  ./gradlew assembleDebug

workflows:
  version: 2
  version_and_build:
    jobs:
      - build_apk